spec: unset __brp_linkdupes to unbreak building inside mkosi
Building the rpm inside a sandbox in mkosi without selinux fails.
As a quick workaround just %undefine __brp_linkdupes

The original error:
```
+ /usr/bin/linkdupes --brp /var/tmp/BUILD/varlink-httpd-0.1.0-build/BUILDROOT/usr
Error: selabel_open() failed

Caused by:
    No such file or directory (os error 2)
error: Bad exit status from /var/tmp/rpm-tmp.XXXXXX (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.XXXXXX (%install)
```